MvcOtomasyon/MvcOtomasyon/Controllers/MusterilerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOtomasyon.Models.Entity;

namespace MvcOtomasyon.Controllers
{
    public class MusterilerController : Controller
    {
        // GET: Musteriler
        SatisVTEntities db = new SatisVTEntities();
        public ActionResult Index(string p)
        {
            var degerler = from d in db.TBLMUSTERI select d;
            if (!string.IsNullOrEmpty(p))
            {
                degerler = degerler.Where(m => m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());
            //var degerler = db.TBLMUSTERI.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERI p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMusteri");
            }
            
            db.TBLMUSTERI.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SIL(int id)
        {
            var musteriler =db.TBLMUSTERI.Find(id);
            db.TBLMUSTERI.Remove(musteriler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var musteri = db.TBLMUSTERI.Find(id);
            return View("MusteriGetir",musteri);
        }
        public ActionResult Guncelle(TBLMUSTERI p1) 
        { 
            
            var mus = db.TBLMUSTERI.Find(p1.MUSTERIID);
            mus.MUSTERIAD = p1.MUSTERIAD;
            mus.MUSTERISEHIR=p1.MUSTERISEHIR;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MvcOtomasyon/MvcOtomasyon/Views/Musteriler/Index.cshtml
@using MvcOtomasyon.Models.Entity
@model List<TBLMUSTERI>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Mainlayout.cshtml";
}

@using (Html.BeginForm("Index", "Musteriler", FormMethod.Get))
            {
                <p>
                    <b>Aranacak Müşteri Adı:</b> @Html.TextBox("p")
                    <input type="submit" value="Ara" />
                </p>
            }

<table class="table table-bordered ">
    <tr>
        <th>Müşteri Numarası</th>
        <th>Müşteri Adı</th>
        <th>Müşteri Soyadı</th>
        <th>Şehir</th>
    </tr>
    <tbody>
        @foreach (var musteri in Model)
        {
            <tr>
                <th>@musteri.MUSTERIID</th>
                <td>@musteri.MUSTERIAD</td>
                <td>@musteri.MUSTERSOYAD</td>
                <td>@musteri.MUSTERISEHIR</td>
                <td><a href="/MUSTERILER/SIL/@musteri.MUSTERIID" 
                       class="btn btn-danger"
                       onclick="return confirm('Bu müşteriyi silmek istediğinize emin misiniz?')"
                       >SİL</a></td>
                <td><a href="/MUSTERILER/MusteriGetir/@musteri.MUSTERIID" class="btn btn-success">GÜNCELLE</a></td>

            </tr>
        }
    </tbody>
</table>
<a href="/MUSTERILER/YeniMusteri" class="btn btn-primary">Yeni Müşteri Ekle</a>

MvcOtomasyon/MvcOtomasyon/Views/Musteriler/MusteriGetir.cshtml
@model MvcOtomasyon.Models.Entity.TBLMUSTERI
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_Mainlayout.cshtml";
}

@using (Html.BeginForm("Guncelle","Musteriler", FormMethod.Post))
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.MUSTERIID)
                    @Html.TextBoxFor(m => m.MUSTERIID, new { @class = "form-control", @style = "text-transform:uppercase" })
                    <br />
                    @Html.LabelFor(m => m.MUSTERIAD)
                    @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control", @style = "text-transform:uppercase" })
                    <br />
                    @Html.LabelFor(m => m.MUSTERSOYAD)
                    @Html.TextBoxFor(m => m.MUSTERSOYAD, new { @class = "form-control", @style = "text-transform:uppercase" })
                    <br />
                    @Html.LabelFor(m => m.MUSTERISEHIR)
                    @Html.TextBoxFor(m => m.MUSTERISEHIR, new { @class = "form-control", @style = "text-transform:uppercase" })
                </div>
                <div>
                    <button class="btn btn-warning">Güncelle</button>
                </div>
            }

MvcOtomasyon/MvcOtomasyon/Views/Musteriler/YeniMusteri.cshtml
@model MvcOtomasyon.Models.Entity.TBLMUSTERI
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_Mainlayout.cshtml";
}

<form method="post" class="form-group">
    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m => m.MUSTERIAD, new { @class = "form-control", @style = "text-transform:uppercase" })
        @Html.ValidationMessageFor(m => m.MUSTERIAD, "", new { @style = "color:red" })
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        @Html.TextBoxFor(m => m.MUSTERSOYAD, new { @class = "form-control", @style = "text-transform:uppercase" })
        @Html.ValidationMessageFor(m => m.MUSTERSOYAD, "", new { @style = "color:red" })
    </div>
    <div>
        <label>Şehir</label>
        @Html.TextBoxFor(m => m.MUSTERISEHIR, new { @class = "form-control", @style = "text-transform:uppercase" })
        @Html.ValidationMessageFor(m => m.MUSTERISEHIR, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-primary">Müşteri Ekle</button>
    </div>

</form>